version: '3.8'
services:
  messagebus:
    image: rabbitmq:latest
    container_name: messagebus
    hostname: "messagebus"
    labels:
      NAME: "messagebus"
    ports:
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - app-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app-network
    ports:
      - '27017:27017'
  db-exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      - MONGODB_URI=mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "9216:9216"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: "mongodb://root:root@mongo:27017/"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
  prometheus:
    build:
      context: prom_volume/
      dockerfile: Dockerfile
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - db-exporter
  grafana:
    build: ./grafana
    ports:
      - 3005:3000
networks:
  app-network:

volumes:
  mongo-data:
