version: '3.8'
services:
  messagebus:
    image: rabbitmq:latest
    container_name: messagebus
    hostname: "messagebus"
    labels:
      NAME: "messagebus"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - app-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: "mongodb://root:root@mongo:27017/"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
