global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'express-api'
    static_configs:
      - targets: ['api:3000']

  - job_name: 'doc-api'
    static_configs:
      - targets: ['document-service:3001']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['db-exporter:9216']

  - job_name: 'mongodb-doc'
    static_configs:
      - targets: ['db-exporter-doc:9216']