name: Bunnyshell - Prepare Preview Environment Configuration
on:
  workflow_run:
    workflows:
      - "API CI"
    types:
      - completed
jobs:
  deploy_prepare:
    name: Prepare Deployment of Environment
    uses: bunnyshell/workflows/.github/workflows/prepare-configuration.yaml@v2
    with:
      bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml
      allowed-users: "*"
      git-ref: refs/pull/${{ github.event.number || github.event.issue.number }}/head
      restricted-files: |
        .bunnyshell/*
